swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
  version: production

basePath: /JSSResource/
produces:
  - application/json
consumes:
  - application/json
security:
  - basicAuth: []

paths:
  /accounts:
    get:
      summary: Finds all accounts
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
